version: '3.9'

networks:
  net_bookstack:
    external:
      name: net_bookstack

services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack:version-v21.04.2
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://books.volnet.dev
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=
      - DB_DATABASE=bookstackapp
    volumes:
      - /data/bookstack/data:/config
    restart: unless-stopped
    depends_on:
      - bookstack_db
    networks:
      - net_bookstack

  bookstack_db:
    image: ghcr.io/linuxserver/mariadb:version-110.4.18mariabionic
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=
      - TZ=Asia/Kuala_Lumpur
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=
    volumes:
      - /data/bookstack/mysql:/config
    restart: unless-stopped
    networks:
      - net_bookstack
