version: '2'

services:

  openvpn:
    container_name: openvpn
    restart: unless-stopped
    image: wheelybird/openvpn-ldap-otp:v1.5
    environment:
      - OVPN_SERVER_CN=vpn.example.com
      - LDAP_URI=ldap://ldap:389
      - LDAP_BASE_DN=ou=People,dc=example,dc=com
      - OVPN_ENABLE_COMPRESSION=false
      - KEY_LENGTH=4096
      - ENABLE_OTP=true
      - OVPN_DNS_SERVERS=8.8.8.8,1.1.1.1
    cap_add:
      - NET_ADMIN
    ports:
      - 1194:1194/udp
